In [49]:
import torch

In [50]:
size = '10k'
d=2
data = torch.load(f'testing_data__d={d}_{size}.pth')['data']
X_pde = data['X_pde']
X_ic = data['X_ic'][:,:-1]
#X = torch.cat((X_pde, X_ic), dim=0)
#X.shape
X = X_pde
d = X.shape[-1]-1
X_pde[:,-1].max(), X.shape, d

(tensor(4.9998), torch.Size([10000, 3]), 2)

In [51]:
x = X[X[:, -1].argsort()]   # sort by time
n_parts = 4
parts = torch.chunk(x, n_parts, dim=0)        # roughly equal number of rows

bins = []
times = []
for i in range(len(parts)):
    times.append( parts[i][:,-1].max().item() )
    bins.append( parts[i][:,:-1].numpy() )
times

[1.2497260570526123, 2.4996654987335205, 3.749957323074341, 4.999752521514893]

In [52]:
bins

[array([[0.7083173 , 0.07121699],
        [0.5242544 , 0.2999125 ],
        [0.10177239, 0.6723387 ],
        ...,
        [0.81200427, 0.62872624],
        [0.42959878, 0.61808103],
        [0.29665333, 0.62937725]], shape=(2500, 2), dtype=float32),
 array([[0.7180331 , 0.12941305],
        [0.01458634, 0.11873313],
        [0.38672498, 0.47627264],
        ...,
        [0.99973017, 0.755278  ],
        [0.19827764, 0.60980296],
        [0.84275305, 0.43099272]], shape=(2500, 2), dtype=float32),
 array([[0.06767501, 0.8270742 ],
        [0.9262668 , 0.6988292 ],
        [0.6669258 , 0.19370909],
        ...,
        [0.7031012 , 0.37512282],
        [0.9702118 , 0.99260575],
        [0.09567441, 0.90668076]], shape=(2500, 2), dtype=float32),
 array([[0.94951856, 0.6997914 ],
        [0.86924833, 0.38092244],
        [0.6892808 , 0.97324795],
        ...,
        [0.37056804, 0.65580195],
        [0.78204167, 0.50308955],
        [0.86676687, 0.7173442 ]], shape=(2500, 2), dtype=float3

In [53]:
import numpy as np
np.savez_compressed(f'X_pde_bins_d={d}_{size}.npz', X_pde_bins=np.array(bins), times=np.array(times))
np.savez_compressed(f'X_ic_d={d}_{size}.npz', X_ic=X_ic.numpy())

In [54]:
X_ic.numpy()

array([[0.9255907 , 0.13364379],
       [0.52615285, 0.27119517],
       [0.16567925, 0.06629497],
       ...,
       [0.29161048, 0.3606138 ],
       [0.22412705, 0.70298296],
       [0.4259561 , 0.9823948 ]], shape=(1250, 2), dtype=float32)

In [55]:
data = np.load(f'X_ic_d={d}_{size}.npz')
data["X_ic"].shape

(1250, 2)

In [56]:
data = np.load(f'X_pde_bins_d={d}_{size}.npz')
data['X_pde_bins'].shape, data['times'].shape

((4, 2500, 2), (4,))