In [1]:
import torch

In [2]:
def gelu(x):
    return x * 0.5 * (1.0 + torch.erf(x / 1.41421))

@torch.compile
def gelu_com(x):
    return x * 0.5 * (1.0 + torch.erf(x / 1.41421))

In [16]:
X = torch.rand(100_000_000)

In [29]:
gelu(X)

tensor([0.3223, 0.6268, 0.1019,  ..., 0.0145, 0.1120, 0.3580])

In [25]:
gelu_com(torch.rand(10))

tensor([0.2739, 0.4956, 0.0607, 0.1346, 0.6052, 0.1891, 0.0284, 0.6305, 0.4781,
        0.0805])

In [28]:
gelu_com(X)

tensor([0.3223, 0.6268, 0.1019,  ..., 0.0145, 0.1120, 0.3580])