In [1]:
import torch

In [2]:
# consider a function in 3d
def y_fun(x):
    return x[0]**3 - (x[1]**2 + x[2]**2)

x = torch.tensor([0.0, 1.0, 2.0], requires_grad=True)
d = 3

In [3]:
y = y_fun(x)
y

tensor(-5., grad_fn=<SubBackward0>)

In [ ]:
g = torch.autograd.grad(
    inputs=x,
    outputs=y,
    create_graph=True,
    retain_graph=True,
)[0]
g

tensor([ 0., -2., -4.], grad_fn=<AddBackward0>)

In [5]:
torch.autograd.grad(
    inputs=x,
    outputs=g[0],
    retain_graph=True,
    create_graph=False,
)[0]

tensor([0., 0., 0.])

In [6]:
torch.autograd.grad(
    inputs=x,
    outputs=g[1],
    retain_graph=True,
    create_graph=False,
)[0]

tensor([ 0., -2.,  0.])

In [7]:
torch.autograd.grad(
    inputs=x,
    outputs=g[2],
    retain_graph=False,
    create_graph=False,
)[0]

tensor([ 0.,  0., -2.])