In [40]:
import torch

In [41]:
# consider a function in 3d
def y_fun(x):
    return (x[:,0]**3 - (x[:,1]**2 + x[:,2]**2)).unsqueeze(dim=1)
    #return (x[:,0]**3 - (x[:,1]**2 + x[:,2]**2))

x = torch.tensor([
    [0.0, 1.0, 2.0],
    [1.0, 2.0, 0.0],
    [2.0, 0.0, 1.0],
    [1.0, 1.0, 1.0],
    [-1.0, -1.0, -1.0],
], requires_grad=True)
bs, d = x.shape
bs, d

(5, 3)

In [42]:
y = y_fun(x)
y

tensor([[-5.],
        [-3.],
        [ 7.],
        [-1.],
        [-3.]], grad_fn=<UnsqueezeBackward0>)

In [43]:
g = torch.autograd.grad(
    inputs=x,
    outputs=y,
    grad_outputs=torch.ones_like(y),
    create_graph=True,
    retain_graph=True,
)[0]
g

tensor([[ 0., -2., -4.],
        [ 3., -4.,  0.],
        [12.,  0., -2.],
        [ 3., -2., -2.],
        [ 3.,  2.,  2.]], grad_fn=<AddBackward0>)

In [44]:
torch.autograd.grad(
    inputs=x,
    outputs=g[:,0],
    grad_outputs=torch.ones_like(g[:,0]),
    retain_graph=True,
    create_graph=False,
)[0]

tensor([[ 0.,  0.,  0.],
        [ 6.,  0.,  0.],
        [12.,  0.,  0.],
        [ 6.,  0.,  0.],
        [-6.,  0.,  0.]])

In [45]:
torch.autograd.grad(
    inputs=x,
    outputs=g[:,1],
    grad_outputs=torch.ones_like(g[:,1]),
    retain_graph=True,
    create_graph=False,
)[0]

tensor([[ 0., -2.,  0.],
        [ 0., -2.,  0.],
        [ 0., -2.,  0.],
        [ 0., -2.,  0.],
        [ 0., -2.,  0.]])

In [46]:
torch.autograd.grad(
    inputs=x,
    outputs=g[:,2],
    grad_outputs=torch.ones_like(g[:,2]),
    retain_graph=False,
    create_graph=False,
)[0]

tensor([[ 0.,  0., -2.],
        [ 0.,  0., -2.],
        [ 0.,  0., -2.],
        [ 0.,  0., -2.],
        [ 0.,  0., -2.]])