In [1]:
import torch

In [44]:
alpha = None
a = alpha if alpha else 3.0
a

3.0

In [53]:
vec = torch.ones(4)

In [57]:
vec is not None

True

In [59]:
a = vec if vec is not None else 7.4
a

tensor([1., 1., 1., 1.])

In [39]:
#X = torch.rand((10,3))
X = torch.tensor([[0.3690, 0.0935, 0.1858],
        [0.0066, 0.3421, 0.6771],
        [0.9154, 0.4860, 0.0361],
        [0.4047, 0.7489, 0.5959],
        [0.3781, 0.4999, 0.0909],
        [0.5760, 0.7195, 0.6580],
        [0.0447, 0.2807, 0.0327],
        [0.0573, 0.8718, 0.9917],
        [0.9047, 0.6509, 0.4256],
        [0.9901, 0.9342, 0.8049]])

pack = TravellingGaussPacket_v2(2)

In [41]:
pack.pde_residual(X, X[:,-1:], X[:,:-1], X[:,:-1])

tensor([[ 6.9910,  6.9797],
        [11.7931, 11.7929],
        [ 1.1539,  1.1260],
        [ 9.4160,  9.4037],
        [ 6.5990,  6.5875],
        [ 9.5215,  9.5040],
        [ 2.8543,  2.8529],
        [12.4298, 12.4281],
        [ 6.3746,  6.3471],
        [11.2536, 11.2234]])

In [42]:
pack.u_analytic(X)
pack.f(X)

tensor([[-4.4762],
        [-1.4772],
        [-1.3913],
        [-0.6805],
        [-5.5387],
        [ 0.0132],
        [-2.3943],
        [ 2.6381],
        [-0.6654],
        [ 0.1641]])